



















// This file was automatically generated by the PetaPoco T4 Template
// Do not make changes directly to this file - edit the template instead
// 
// The following connection settings were used to generate this file
// 
//     Connection String Name: `AdouConnection`
//     Provider:               `System.Data.SqlClient`
//     Connection String:      `Data Source=.;Initial Catalog=adou;MultipleActiveResultSets=True;user id=sa;password=**zapped**;`
//     Schema:                 ``
//     Include Views:          `False`



using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using PetaPoco;

namespace Adou.Entity.PetaPocoModels.AdouModel
{

	public partial class PetaPocoAdouDB : Database
	{
		public PetaPocoAdouDB() 
			: base("AdouConnection")
		{
			CommonConstruct();
		}

		public PetaPocoAdouDB(string connectionStringName) 
			: base(connectionStringName)
		{
			CommonConstruct();
		}
		
		partial void CommonConstruct();
		
		public interface IFactory
		{
			PetaPocoAdouDB GetInstance();
		}
		
		public static IFactory Factory { get; set; }
        public static PetaPocoAdouDB GetInstance()
        {
			if (_instance!=null)
				return _instance;
				
			if (Factory!=null)
				return Factory.GetInstance();
			else
				return new PetaPocoAdouDB();
        }

		[ThreadStatic] static PetaPocoAdouDB _instance;
		
		public override void OnBeginTransaction()
		{
			if (_instance==null)
				_instance=this;
		}
		
		public override void OnEndTransaction()
		{
			if (_instance==this)
				_instance=null;
		}
        

		public class Record<T> where T:new()
		{
			public static PetaPocoAdouDB repo { get { return PetaPocoAdouDB.GetInstance(); } }
			public bool IsNew() { return repo.IsNew(this); }
			public object Insert() { return repo.Insert(this); }

			public void Save() { repo.Save(this); }
			public int Update() { return repo.Update(this); }

			public int Update(IEnumerable<string> columns) { return repo.Update(this, columns); }
			public static int Update(string sql, params object[] args) { return repo.Update<T>(sql, args); }
			public static int Update(Sql sql) { return repo.Update<T>(sql); }
			public int Delete() { return repo.Delete(this); }
			public static int Delete(string sql, params object[] args) { return repo.Delete<T>(sql, args); }
			public static int Delete(Sql sql) { return repo.Delete<T>(sql); }
			public static int Delete(object primaryKey) { return repo.Delete<T>(primaryKey); }
			public static bool Exists(object primaryKey) { return repo.Exists<T>(primaryKey); }
			public static bool Exists(string sql, params object[] args) { return repo.Exists<T>(sql, args); }
			public static T SingleOrDefault(object primaryKey) { return repo.SingleOrDefault<T>(primaryKey); }
			public static T SingleOrDefault(string sql, params object[] args) { return repo.SingleOrDefault<T>(sql, args); }
			public static T SingleOrDefault(Sql sql) { return repo.SingleOrDefault<T>(sql); }
			public static T FirstOrDefault(string sql, params object[] args) { return repo.FirstOrDefault<T>(sql, args); }
			public static T FirstOrDefault(Sql sql) { return repo.FirstOrDefault<T>(sql); }
			public static T Single(object primaryKey) { return repo.Single<T>(primaryKey); }
			public static T Single(string sql, params object[] args) { return repo.Single<T>(sql, args); }
			public static T Single(Sql sql) { return repo.Single<T>(sql); }
			public static T First(string sql, params object[] args) { return repo.First<T>(sql, args); }
			public static T First(Sql sql) { return repo.First<T>(sql); }
			public static List<T> Fetch(string sql, params object[] args) { return repo.Fetch<T>(sql, args); }
			public static List<T> Fetch(Sql sql) { return repo.Fetch<T>(sql); }
			public static List<T> Fetch(long page, long itemsPerPage, string sql, params object[] args) { return repo.Fetch<T>(page, itemsPerPage, sql, args); }
			public static List<T> Fetch(long page, long itemsPerPage, Sql sql) { return repo.Fetch<T>(page, itemsPerPage, sql); }
			public static List<T> SkipTake(long skip, long take, string sql, params object[] args) { return repo.SkipTake<T>(skip, take, sql, args); }
			public static List<T> SkipTake(long skip, long take, Sql sql) { return repo.SkipTake<T>(skip, take, sql); }
			public static Page<T> Page(long page, long itemsPerPage, string sql, params object[] args) { return repo.Page<T>(page, itemsPerPage, sql, args); }
			public static Page<T> Page(long page, long itemsPerPage, Sql sql) { return repo.Page<T>(page, itemsPerPage, sql); }
			public static IEnumerable<T> Query(string sql, params object[] args) { return repo.Query<T>(sql, args); }
			public static IEnumerable<T> Query(Sql sql) { return repo.Query<T>(sql); }

		}

	}
	



	/// <summary>
	/// 账号管理
	/// </summary>    

	[TableName("dbo.adAccount")]



	[PrimaryKey("ID")]




	[ExplicitColumns]

    public partial class adAccount : PetaPocoAdouDB.Record<adAccount>  
    {

		/// <summary>
		/// 编号
		/// </summary>


		[Column] public int ID { get; set; }



		/// <summary>
		/// 名称
		/// </summary>


		[Column] public string Name { get; set; }



		/// <summary>
		/// 邮箱
		/// </summary>


		[Column] public string Email { get; set; }



		/// <summary>
		/// 手机号
		/// </summary>


		[Column] public string Phone { get; set; }



		/// <summary>
		/// 链接
		/// </summary>


		[Column] public string Url { get; set; }



		/// <summary>
		/// 账号
		/// </summary>


		[Column] public string Account { get; set; }



		/// <summary>
		/// 密码
		/// </summary>


		[Column] public string Pwd { get; set; }



		/// <summary>
		/// 备注
		/// </summary>


		[Column] public string Remark { get; set; }



		/// <summary>
		/// 描述
		/// </summary>


		[Column] public string Description { get; set; }



		/// <summary>
		/// 创建时间
		/// </summary>


		[Column] public DateTime? CreateTime { get; set; }



		/// <summary>
		/// 创建用户编号
		/// </summary>


		[Column] public long? CreateUserId { get; set; }



		/// <summary>
		/// 修改时间
		/// </summary>


		[Column] public DateTime? UpdateTime { get; set; }



		/// <summary>
		/// 修改用户编号
		/// </summary>


		[Column] public long? UpdateUserId { get; set; }



		/// <summary>
		/// 标识列
		/// </summary>


		[Column] public Guid? TableId { get; set; }



		/// <summary>
		/// 
		/// </summary>


		[Column] public string Adous { get; set; }



	}

	/// <summary>
	/// 
	/// </summary>    

	[TableName("dbo.adArticle")]



	[PrimaryKey("Id")]




	[ExplicitColumns]

    public partial class adArticle : PetaPocoAdouDB.Record<adArticle>  
    {

		/// <summary>
		/// 
		/// </summary>


		[Column] public int Id { get; set; }



		/// <summary>
		/// 文章标题
		/// </summary>


		[Column] public string Title { get; set; }



		/// <summary>
		/// 关键词
		/// </summary>


		[Column] public string Keywords { get; set; }



		/// <summary>
		/// 描述
		/// </summary>


		[Column] public string Description { get; set; }



		/// <summary>
		/// 图片
		/// </summary>


		[Column] public string Picture { get; set; }



		/// <summary>
		/// 文件
		/// </summary>


		[Column] public string DocumentFile { get; set; }



		/// <summary>
		/// 内容
		/// </summary>


		[Column] public string Contents { get; set; }



		/// <summary>
		/// 创建时间
		/// </summary>


		[Column] public DateTime? CreateTime { get; set; }



		/// <summary>
		/// 创建用户
		/// </summary>


		[Column] public int? CreateUserId { get; set; }



		/// <summary>
		/// 修改时间
		/// </summary>


		[Column] public DateTime? ModifyTime { get; set; }



		/// <summary>
		/// 修改用户
		/// </summary>


		[Column] public int? ModifyUserId { get; set; }



		/// <summary>
		/// 是否有效
		/// </summary>


		[Column] public bool? IsValid { get; set; }



	}

	/// <summary>
	/// 
	/// </summary>    

	[TableName("dbo.adInterfaceAccount")]



	[PrimaryKey("InterfaceId")]




	[ExplicitColumns]

    public partial class adInterfaceAccount : PetaPocoAdouDB.Record<adInterfaceAccount>  
    {

		/// <summary>
		/// 
		/// </summary>


		[Column] public long InterfaceId { get; set; }



		/// <summary>
		/// 商户名称
		/// </summary>


		[Column] public string MerchantName { get; set; }



		/// <summary>
		/// 商户IP地址
		/// </summary>


		[Column] public string MerchantIP { get; set; }



		/// <summary>
		/// 商户Code
		/// </summary>


		[Column] public string MerchantCode { get; set; }



		/// <summary>
		/// 商户类型
		/// </summary>


		[Column] public int? MerchantType { get; set; }



		/// <summary>
		/// 商户唯一Key
		/// </summary>


		[Column] public string MerchantKey { get; set; }



		/// <summary>
		/// 证书地址 私钥和公钥
		/// </summary>


		[Column] public string CertificateAddress { get; set; }



		/// <summary>
		/// 证书密码
		/// </summary>


		[Column] public string CertificatePassword { get; set; }



		/// <summary>
		/// 是否有效  0已删除  1有效
		/// </summary>


		[Column] public int? IsValid { get; set; }



		/// <summary>
		/// 创建时间
		/// </summary>


		[Column] public DateTime? CreateTime { get; set; }



		/// <summary>
		/// 创建用户
		/// </summary>


		[Column] public long? CreateUserID { get; set; }



		/// <summary>
		/// 修改时间
		/// </summary>


		[Column] public DateTime? UpdateTime { get; set; }



		/// <summary>
		/// 修改用户
		/// </summary>


		[Column] public long? UpdateUserID { get; set; }



		/// <summary>
		/// 
		/// </summary>


		[Column] public Guid? TableID { get; set; }



	}

	/// <summary>
	/// 
	/// </summary>    

	[TableName("dbo.adMenus")]



	[PrimaryKey("Id")]




	[ExplicitColumns]

    public partial class adMenu : PetaPocoAdouDB.Record<adMenu>  
    {

		/// <summary>
		/// 
		/// </summary>


		[Column] public int Id { get; set; }



		/// <summary>
		/// 
		/// </summary>


		[Column] public string Title { get; set; }



		/// <summary>
		/// 
		/// </summary>


		[Column] public string MenuIcon { get; set; }



		/// <summary>
		/// 
		/// </summary>


		[Column] public string MenuUrl { get; set; }



		/// <summary>
		/// 父级编号
		/// </summary>


		[Column] public int? FatherId { get; set; }



		/// <summary>
		/// 级别
		/// </summary>


		[Column] public int? LevelId { get; set; }



		/// <summary>
		/// 
		/// </summary>


		[Column] public DateTime? CreateTime { get; set; }



		/// <summary>
		/// 
		/// </summary>


		[Column] public string CreateUser { get; set; }



		/// <summary>
		/// 
		/// </summary>


		[Column] public DateTime? ModifyTime { get; set; }



		/// <summary>
		/// 
		/// </summary>


		[Column] public string ModifyUser { get; set; }



		/// <summary>
		/// 是有效 0无效 1有效
		/// </summary>


		[Column] public int? IstValid { get; set; }



	}

	/// <summary>
	/// 
	/// </summary>    

	[TableName("dbo.adUser")]



	[PrimaryKey("ID")]




	[ExplicitColumns]

    public partial class adUser : PetaPocoAdouDB.Record<adUser>  
    {

		/// <summary>
		/// 用户编号
		/// </summary>


		[Column] public long ID { get; set; }



		/// <summary>
		/// 用户名称
		/// </summary>


		[Column] public string UserName { get; set; }



		/// <summary>
		/// 用户密码
		/// </summary>


		[Column] public string UserPwd { get; set; }



		/// <summary>
		/// 用户头像
		/// </summary>


		[Column] public string UserHead { get; set; }



		/// <summary>
		/// 0为超级管理员
		/// </summary>


		[Column] public int? UserType { get; set; }



		/// <summary>
		/// 用户状态 0启用 1禁用 2黑名单
		/// </summary>


		[Column] public int? UserStatus { get; set; }



		/// <summary>
		/// 角色编号
		/// </summary>


		[Column] public long? RoleId { get; set; }



		/// <summary>
		/// 创建时间
		/// </summary>


		[Column] public DateTime? CreateTime { get; set; }



		/// <summary>
		/// 创建用户编号
		/// </summary>


		[Column] public long? CreateUserId { get; set; }



		/// <summary>
		/// 修改时间
		/// </summary>


		[Column] public DateTime? UpdateTime { get; set; }



		/// <summary>
		/// 修改用户编号
		/// </summary>


		[Column] public long? UpdateUserId { get; set; }



		/// <summary>
		/// 
		/// </summary>


		[Column] public Guid? TableId { get; set; }



	}

	/// <summary>
	/// 
	/// </summary>    

	[TableName("dbo.FieldDictionary")]



	[PrimaryKey("ID")]




	[ExplicitColumns]

    public partial class FieldDictionary : PetaPocoAdouDB.Record<FieldDictionary>  
    {

		/// <summary>
		/// 
		/// </summary>


		[Column] public int ID { get; set; }



		/// <summary>
		/// 
		/// </summary>


		[Column] public int? TableID { get; set; }



		/// <summary>
		/// 
		/// </summary>


		[Column] public string FieldName { get; set; }



		/// <summary>
		/// 
		/// </summary>


		[Column] public string FieldType { get; set; }



		/// <summary>
		/// 
		/// </summary>


		[Column] public string Description { get; set; }



		/// <summary>
		/// 
		/// </summary>


		[Column] public DateTime? CreateTime { get; set; }



		/// <summary>
		/// 
		/// </summary>


		[Column] public DateTime? UpdateTime { get; set; }



		/// <summary>
		/// 
		/// </summary>


		[Column] public int? CreateUserID { get; set; }



		/// <summary>
		/// 
		/// </summary>


		[Column] public int? UpdateUserID { get; set; }



		/// <summary>
		/// 是否删除 0删除  
		/// </summary>


		[Column] public int? IsValid { get; set; }



		/// <summary>
		/// 是否显示  0不显示
		/// </summary>


		[Column] public int? IsVisible { get; set; }



	}

	/// <summary>
	/// 
	/// </summary>    

	[TableName("dbo.TableDictionary")]



	[PrimaryKey("ID")]




	[ExplicitColumns]

    public partial class TableDictionary : PetaPocoAdouDB.Record<TableDictionary>  
    {

		/// <summary>
		/// 
		/// </summary>


		[Column] public int ID { get; set; }



		/// <summary>
		/// 
		/// </summary>


		[Column] public string TableName { get; set; }



		/// <summary>
		/// 
		/// </summary>


		[Column] public string Description { get; set; }



		/// <summary>
		/// 
		/// </summary>


		[Column] public DateTime? CreateTime { get; set; }



		/// <summary>
		/// 
		/// </summary>


		[Column] public DateTime? UpdateTime { get; set; }



		/// <summary>
		/// 
		/// </summary>


		[Column] public int? CreateUserID { get; set; }



		/// <summary>
		/// 
		/// </summary>


		[Column] public int? UpdateUserID { get; set; }



		/// <summary>
		/// 
		/// </summary>


		[Column] public int? IsValid { get; set; }



		/// <summary>
		/// 
		/// </summary>


		[Column] public int? IsVisible { get; set; }



	}


}
